### ISSUE TITLE
fixed img_size (224&384)?

### ISSUE THREAD

**Issue by zebrazjx** [Timm-Jittor/Jittor-Image-Models#2]
Thanks for your work!
I  have a questition, can this swin transformer only enter a fixed size（224*224) ？my img_size=1024*1024, how can i do to train it?

**Comment by Jittor-Image-Models** [comment]
For Transformers, maybe you could refer:&nbsp;https://blog.csdn.net/qq_39967751/article/details/123666686
For Swin Transformers,&nbsp; official SwinV2 code gives some samples (pretrain 192 but finetune 384).
It is a pity that jimm do not support change image size in ViTs at this moment. But in the latest version of timm, just change the input size when ceate the model is OK.
Hope this can help you.  
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Aug 20, 2022 08:28 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[Jittor-Image-Models/Jittor-Image-Models] fixed img_size (224&amp;384)? (Issue #2)

&nbsp;



 
Thanks for your work!
 I  have a questition, can this swin transformer only enter a fixed size（224224) ？my img_size=10241024, how can i do to train it?

**Comment by zebrazjx** [comment]
Thanks a lot ,another questions I want to ask：
1、Because my task must use the jittor and JDet, there is no swin transformer provided,i must create it by myself, so I swa yours is very good for me, but my img-size=1024, if i tile the img from 1024 to 224 in order to train the swin transformer, it's a good idea? or i use other models such as efficienet to train 1024size ? Which one do you recommend more？or others?
2、can your efficienet change the img_size to 1024?

I will appreciate it if you could give me some advice,thanks very much(Please excuse my poor English）

**Comment by Jittor-Image-Models** [comment]
Hi, change the input size of img for each CNN (including&nbsp;EfficientNet) can work.
It is also&nbsp;reasonable to&nbsp;tile the img from 1024 to 224 to train the swin transformer, but I suggest that you can do some experiments to verify that if the image size has a significant impact or not.
&nbsp;


&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, Aug 21, 2022 12:07 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Jittor-Image-Models/Jittor-Image-Models] fixed img_size (224&amp;384)? (Issue #2)

&nbsp;



 
Thanks a lot ,another questions I want to ask：
 1、Because my task must use the jittor and JDet, there is no swin transformer provided,i must create it by myself, so I swa yours is very good for me, but my img-size=1024, if i tile the img from 1024 to 224 in order to train the swin transformer, it's a good idea? or i use other models such as efficienet to train 1024size ? Which one do you recommend more？or others?
 2、can your efficienet change the img_size to 1024?
 
I will appreciate it if you could give me some advice,thanks very much(Please excuse my poor English）
